spring:
  datasource:
      url: "jdbc:mysql://localhost:3306/smartphone?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
      driverClassName: com.mysql.jdbc.Driver
      username: admin
      password: 2580Sabi2580
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
  liquibase:
    change-log: "classpath:/liquibase/liquibase-changeLog.xml"
